# Generated by Django 2.0.1 on 2018-02-02 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geburtstage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geburtstag', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
